# Generated by Django 5.1.3 on 2024-11-28 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil_descripcion",
                    models.TextField(
                        verbose_name="Descripción de perfil (estilo LinkedIn)"
                    ),
                ),
                (
                    "empresas_y_logros",
                    models.TextField(
                        verbose_name="Empresas en las que ha trabajado y sus logros"
                    ),
                ),
                (
                    "anos_experiencia_liderazgo",
                    models.PositiveIntegerField(
                        verbose_name="¿Cuántos años de experiencia tiene en posiciones de liderazgo o dirección?"
                    ),
                ),
                (
                    "numero_juntas_anteriores",
                    models.PositiveIntegerField(
                        verbose_name="¿Cuántas juntas directivas ha integrado anteriormente?"
                    ),
                ),
                (
                    "ha_ocupado_posicion_ejecutiva",
                    models.BooleanField(
                        default=False,
                        verbose_name="¿Ha ocupado posiciones ejecutivas (CEO, CFO, COO, etc.)?",
                    ),
                ),
                (
                    "anos_en_posicion_ejecutiva",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Si respondió 'Sí', ¿cuánto tiempo ocupó esa posición? (Años)",
                    ),
                ),
                (
                    "horas_mensuales_disponibles",
                    models.PositiveIntegerField(
                        verbose_name="¿Cuántas horas mensuales puede dedicar al trabajo de la junta?"
                    ),
                ),
                (
                    "competencias",
                    models.CharField(
                        max_length=255,
                        verbose_name="Competencias de mayor conocimiento o experticia (tecnología, marketing, ventas, etc.)",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
