# Generated by Django 5.1.3 on 2024-11-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userformdata",
            name="ha_ocupado_posicion_ejecutiva",
            field=models.BooleanField(
                default=False, verbose_name="¿Ha ocupado posiciones ejecutivas?"
            ),
        ),
    ]
