# Generated by Django 5.1.3 on 2024-12-01 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_userformdata_ha_ocupado_posicion_ejecutiva"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userformdata",
            name="competencias",
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Competencia"),
                ),
                (
                    "user_form_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencias",
                        to="main.userformdata",
                    ),
                ),
            ],
        ),
    ]
